
const fileInput=document.getElementById("mml-file");
if(fileInput){
const fileName=document.getElementById("file-name"),status=document.getElementById("mml-status"),tbody=document.querySelector("#result-table tbody"),csvBtn=document.getElementById("csv-btn");let parsedRows=[];
fileInput.addEventListener("change",()=>{fileName.textContent=fileInput.files[0]?.name||"Choose MML TXT or LOG file";status.textContent=""});
function parseMML(text){const lines=text.split(/\r?\n/),rows=[];let currentNE="",block=[];const flush=()=>{if(!block.length)return;const raw=block.join(" ").replace(/\s+/g," ").trim(),obj=raw.match(/^\s*(?:ADD|MOD|DEL|RMV|DSP|LST|ACT|DEA|SET|SHT|RST)\s+([A-Z0-9_]+)/i),cmd=(raw.match(/^\s*([A-Z]{2,6})\b/i)||[])[1]||"";rows.push({ne:currentNE,command:cmd.toUpperCase(),object:obj?obj[1].toUpperCase():"",raw});block=[]};for(const line of lines){const s=line.trim();if(!s){flush();continue}const ne=s.match(/(?:NE[_ ]?NAME)\s*[:=]\s*([^\s,;]+)/i);if(ne)currentNE=ne[1];if(/^(ADD|MOD|DEL|RMV|DSP|LST|ACT|DEA|SET|SHT|RST)\b/i.test(s)){flush();block=[s]}else if(block.length)block.push(s)}flush();return rows}
document.getElementById("parse-btn").addEventListener("click",async()=>{if(!fileInput.files[0]){status.textContent="Please choose a TXT or LOG file first.";return}const text=await fileInput.files[0].text();parsedRows=parseMML(text);tbody.innerHTML="";if(!parsedRows.length){tbody.innerHTML='<tr><td colspan="5" class="empty">No recognizable MML command blocks found.</td></tr>';csvBtn.disabled=true;status.textContent="0 command blocks found.";return}parsedRows.forEach((r,i)=>{const tr=document.createElement("tr");[i+1,r.ne,r.command,r.object,r.raw].forEach(v=>{const td=document.createElement("td");td.textContent=v||"-";tr.appendChild(td)});tbody.appendChild(tr)});csvBtn.disabled=false;status.textContent=`${parsedRows.length} command block(s) parsed successfully.`)});
document.getElementById("reset-btn").addEventListener("click",()=>{fileInput.value="";fileName.textContent="Choose MML TXT or LOG file";status.textContent="";parsedRows=[];csvBtn.disabled=true;tbody.innerHTML='<tr><td colspan="5" class="empty">Upload a TXT file to see the result.</td></tr>'});
csvBtn.addEventListener("click",()=>{const esc=v=>`"${String(v??"").replace(/"/g,'""')}"`;const csv=[["No","NE_NAME","COMMAND","OBJECT","RAW"],...parsedRows.map((r,i)=>[i+1,r.ne,r.command,r.object,r.raw])].map(r=>r.map(esc).join(",")).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));a.download="mml_parser_result.csv";a.click();URL.revokeObjectURL(a.href)});
}
